repositories:
  - url: "https://github.com/openzim/zimit"
    name: "zimit"
    branch: "main"
  - url: https://github.com/openzim/python-libzim
    name: openZime
    branch: main

paths:
  raw_dir: "data/raw"
  zim_dir: "data/zim"
  sqlite_path: "data/sqlite/docs.db"
  vector_dir: "data/vectors"

