name: Pyrefly Type Check

on:
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      # Install Python dependencies using Poetry
      - name: Install dependencies using Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi

      - name: Install Pyrefly
        run: poetry add pyrefly

      - name: Run Pyrefly Type Checker
        run: poetry run pyrefly check
